source/settings/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

source/web/urls.py
from django.urls import path
from web.views.prestamoView import prestamo, PrestamoView
from web.views.administradorView import AdministradorView,PrestamoEliminarView,PrestamoEditarView

app_name = 'web'

urlpatterns = [
    path("", prestamo, name='prestamo'),
    path("administrador", AdministradorView.as_view(), name='administrador'),
    path("administrador/pretamo/eliminar/<int:pk>", PrestamoEliminarView.as_view(), name='eliminar_prestamo'),
    path("administrador/pretamo/editar/<int:pk>", PrestamoEditarView.as_view(), name='editar_prestamo'),
    path("prestamo", PrestamoView.as_view(), name='solicitar_prestamo')
]

source/web/models/genero.py
from django.db import models


class Genero(models.Model):
    tipo = models.CharField(max_length=20)

    fecha_de_alta = models.DateTimeField(auto_now_add=True, blank=True)
    fecha_de_modificacion = models.DateTimeField(auto_now=True, null=True)

    def __str__(self) -> str:
        return self.tipo

source/web/models/prestamo.py
from django.db import models 
from .usuario import Usuario

class Prestamo(models.Model):
    monto = models.BigIntegerField(default=0)
    aceptado = models.BooleanField(default=False)
    usuario = models.ForeignKey(Usuario, on_delete=models.RESTRICT)

    fecha_de_alta = models.DateTimeField(auto_now_add=True, blank=True)
    fecha_de_modificacion = models.DateTimeField(auto_now=True, null=True)

    def __str__(self) -> str:
        return str(self.monto)

source/web/models/usuario.py
from django.db import models
from .genero import Genero

class Usuario(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    dni = models.CharField(max_length=8, unique=True)
    genero = models.ForeignKey(Genero, on_delete=models.RESTRICT)

    fecha_de_alta = models.DateTimeField(auto_now_add=True, blank=True)
    fecha_de_modificacion = models.DateTimeField(auto_now=True, null=True)

    def __str__(self) -> str:
        return self.dni

source/web/forms/prestamoEditarForm.py
from django import forms
from web.models.prestamo import Prestamo


class PrestamoEditarForm(forms.ModelForm):
    aceptado_auxiliar = forms.BooleanField(required=False)

    class Meta:
        model = Prestamo
        fields = ['monto','aceptado','aceptado_auxiliar']

    class Media:
        js = ('js/web/prestamoEditarForm.js',)

    def save(self, commit: bool = True):
        instancia = super(PrestamoEditarForm, self).save(commit=False)
        
        instancia.aceptado = True if self.cleaned_data['aceptado_auxiliar'] else False

        if commit:
            instancia.save()
        return instancia
    
    def clean_monto(self):
        monto = self.cleaned_data['monto']
        if int(monto) <= 0:
            self.add_error('monto', 'El monto ingresado tiene que ser mayor a $0')
        return monto

source/web/forms/prestamoForm.py
from django import forms
from web.models.usuario import Usuario
from web.models.prestamo import Prestamo
from web.models.genero import Genero


class PrestamoForm(forms.ModelForm):
    nombre = forms.CharField(label='Nombre', max_length='30')
    apellido = forms.CharField(label='Apellido',max_length='30')
    email = forms.EmailField(label='Email', max_length='30')
    dni = forms.CharField(label='DNI', max_length='8')
    genero = forms.ModelChoiceField(queryset=Genero.objects.all())

    class Meta:
        model = Prestamo
        fields = ['dni','email','nombre','apellido','genero','monto']

    class Media:
        js = ('js/web/prestamoForm.js',)

    def save(self, commit = True, aceptado=False):
        genero = Genero.objects.get(tipo=self.cleaned_data['genero'])
        
        obj_usuario, creado = Usuario.objects.get_or_create(
            nombre = self.cleaned_data['nombre'],
            apellido = self.cleaned_data['apellido'],
            email = self.cleaned_data['email'],
            dni = self.cleaned_data['dni'],
            genero = genero
        )

        obj_prestamo = Prestamo.objects.create(
            monto = self.cleaned_data['monto'],
            usuario = obj_usuario,
            aceptado = aceptado
        )

        if commit:
            obj_prestamo.save()
        return obj_prestamo


    def clean_monto(self):
        monto = self.cleaned_data['monto']
        if int(monto) <= 0:
            self.add_error('monto', 'El monto ingresado tiene que ser mayor a $0')
        return monto

        
       

source/web/views/administradorView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from web.models.prestamo import Prestamo
from web.forms.prestamoEditarForm import PrestamoEditarForm
from django.http import JsonResponse
from django.views.generic import(
    ListView,
    DeleteView,
    UpdateView
)



class AdministradorView(LoginRequiredMixin,ListView):
    """
    lista todos los prestamos solicitados ordenados por id de
    forma descendente.
    Solo se puede ingresar si esta logueado
    """
    template_name = 'prestamo/administrador.html'
    model = Prestamo
    context_object_name = 'prestamos'
    ordering = ['-id']


class PrestamoEliminarView(LoginRequiredMixin,DeleteView):
    model = Prestamo
    template_name = 'prestamo/confirmar_eliminar_prestamo.html'
    success_url = reverse_lazy('web:administrador')


class PrestamoEditarView(LoginRequiredMixin,UpdateView):
    model = Prestamo
    form_class = PrestamoEditarForm
    template_name = 'prestamo/editar.html'
    context_object_name = 'prestamo'
    success_url = reverse_lazy('web:administrador')


    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def form_invalid(self, form):
        errors = form.errors
        return JsonResponse({'errors': errors}, status=400)
    

source/web/views/prestamoView.py
# import requests
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView
from web.forms.prestamoForm import PrestamoForm
from web.common.aprobacion_del_prestamo import aprobacion_del_prestamo

def prestamo(request):
    context = {
        'prestamoForm': PrestamoForm() 
    }
    return render(request, 'prestamo/index.html', context)


class PrestamoView(FormView):
    form_class = PrestamoForm
    template_name = reverse_lazy('web:prestamo')
    success_name = reverse_lazy('web:prestamo')

    def form_valid(self, form):
        try:
            dni = form.cleaned_data['dni']
            respuesta = aprobacion_del_prestamo(dni)

            if respuesta['status'] == 'approve' and respuesta['has_error'] == False:
                prestamo = form.save(aceptado=True)
                return JsonResponse({'msg': f'{prestamo.usuario.nombre} {prestamo.usuario.apellido} su prestamo fue aceptado!!!','error':False}, status=201)
            
            elif respuesta['status'] == 'rejected' and respuesta['has_error'] == False:
                prestamo = form.save(aceptado=False)
                return JsonResponse({'msg': f'{prestamo.usuario.nombre} {prestamo.usuario.apellido} lamentablemente su solicitud fue rechazada','error':True}, status=201)
            
            else:
                return JsonResponse({'msg': 'Hubo un error con la solicitud, Intentar Luego','error':True}, status=400)
            
        except Exception as e:
            return JsonResponse({'errors': e.__str__()}, status=400)


    def form_invalid(self, form) -> JsonResponse:
        errors = form.errors
        return JsonResponse({'errors': errors}, status=400)

source/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% block extrastyle %}{% endblock extrastyle %}
</head>
<body>
    {% block main %}
    {% endblock main %}
</body>
</html>

source/templates/base_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Administración{% endblock %}
{% block extrastyle%} 
    <link rel="stylesheet" href="{% static 'css/administrador.css' %}">
{% endblock extrastyle %}


{% block main %}
<div class="wrapper">
    <div class="sidebar">
        <h2>MoniAdmin</h2>
        <ul>
            <li><a href="{% url 'web:prestamo' %}">Home</a></li>
            <li><a href="{% url 'web:administrador' %}">Prestamos</a></li>
        </ul> 
    </div>
    <div class="main_content">
        <div class="info">
           {% block contenido%}
           {% endblock contenido%}
      </div>
    </div>
</div>
{% endblock main %}

source/templates/prestamo/administrador.html
{% extends 'base_admin.html' %}
{% load static %}

{% block contenido %}
    <h1>Administración de los prestamos solicitados</h1>
    <table class="prestamo_admin">
        <tr>
            <th>Id</th>  
            <th>DNI</th>  
            <th>Nombre</th>  
            <th>Apellido</th>  
            <th>Email</th>  
            <th>Genero</th>  
            <th>Monto</th>  
            <th>Estado</th>  
            <th>Operación</th>  
        </tr>
        {% for fila in prestamos %}
            <tr>
                <td>{{fila.id}}</td>
                <td>{{fila.usuario.dni}}</td>
                <td>{{fila.usuario.nombre}}</td>
                <td>{{fila.usuario.apellido}}</td>
                <td>{{fila.usuario.email}}</td>
                <td>{{fila.usuario.genero}}</td>
                <td>{{fila.monto}}</td>
                <td>{% if fila.aceptado %} Aceptado {% else %} Rechazado {% endif %}</td>
                <td class="prestamo_admin__contentbtn">
                    <a class="prestamo_admin--btn btn-eliminar" href="{% url 'web:eliminar_prestamo' fila.id %}">Borrar</a>
                    <a class="prestamo_admin--btn btn-editar" href="{% url 'web:editar_prestamo' fila.id%}">Editar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock contenido%}

source/templates/prestamo/confirmar_eliminar_prestamo.html
{% extends 'base_admin.html' %}

{% load static %}


{% block contenido %}
<section class="prestamo_elmininar">
    <h1>¿Desea eliminar este Prestamo?</h1>
    <h5>Tenga en cuenta que se eliminará el prestamo pero no los datos del usuario</h5>
    <ul>
        <li><span>Dni:</span> {{prestamo.usuario.dni}}</li>
        <li><span>Email:</span> {{prestamo.usuario.email}}</li>
        <li><span>Nombre:</span> {{prestamo.usuario.nombre}}</li>
        <li><span>Apellido:</span> {{prestamo.usuario.apellido}}</li>
        <li><span>Genero:</span> {{prestamo.usuario.genero.tipo}}</li>
        <li><span>Monto:</span> {{prestamo.monto}}</li>
        <li><span>Estado:</span> {% if fila.aceptado %} Aceptado {% else %} Rechazado {% endif %}</li>
    </ul>
    <form method="POST">{% csrf_token %}
        <button type="submit" class="alert button">Confirmar</button>
        <a href="{% url 'web:administrador' %}">Cancelar</a>
    </form>
</section>
{% endblock contenido %}

source/templates/prestamo/editar.html
{% extends 'base_admin.html' %}
{% load static %}

{% block contenido %}
<section class="prestamo_editar"> 
    <h1>Editando el Prestamo</h1>
    <div class="prestamo_editar__contenedor">
        <form method="POST"  class="prestamo__formulario" id="prestamoeditar_formulario">{% csrf_token %}
            <div class="prestamo__formulario--item">
                <label for="dni">Dni</label>
                <input type="text" value="{{prestamo.usuario.dni}}" style="color: gray;" id="dni" name="dni" readonly>
            </div>
            <div class="prestamo__formulario--item">
                <label for="nombre">Nombre</label>
                <input type="text" value="{{prestamo.usuario.nombre}}" style="color: gray;" id="nombre" name="nombre" readonly>
            </div>
            <div class="prestamo__formulario--item">
                <label for="apellido">Apellido</label>
                <input type="text" value="{{prestamo.usuario.apellido}}" style="color: gray;" id="apellido" name="apellido" readonly>
            </div>
            <div class="prestamo__formulario--item">
                <label for="email">Email</label>
                <input type="email" value="{{prestamo.usuario.email}}" style="color: gray;" id="email" name="email" readonly>
            </div>
            <div class="prestamo__formulario--item">
                <label for="genero">Género</label>
                <input type="text" value="{{prestamo.usuario.genero.tipo}}" style="color: gray;" id="genero" name="genero" readonly>
            </div>
            <div class="prestamo__formulario--item">
                <label for="monto">Monto</label>
                <input type="text" value="{{prestamo.monto}}" id="monto" name="monto">
            </div>
            <div class="prestamo__formulario--item" style="position: relative;">
                <label for="aceptado_auxiliar">Aceptado</label>
                {% if prestamo.aceptado %}
                <input 
                    type="checkbox" 
                    id="aceptado_auxiliar" name="aceptado_auxiliar" 
                    class="checkbox_aceptado"
                    checked  
                >
                {% else %}
                <input 
                    type="checkbox" 
                    id="aceptado_auxiliar" name="aceptado_auxiliar" 
                    class="checkbox_aceptado"
                >
                {% endif %}
               
            </div>
            <div class="prestamo__formulario--item">
                <button class="prestamo__submit" type="submit">Editar</button>
            </div> 
        </form>
    </div>
</section>
{{form.media}}
{% endblock contenido %}

source/templates/prestamo/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Prestamo {% endblock %}

{% block main %}
<section class="prestamo">
    <div class="prestamo__lateralIzquierdo" style="background-image: url({% static 'img/prestamo/background-login.webp'%}); background-repeat: no-repeat; background-size: 70% 100%; background-position: center right;">
        <img class="prestamo__logo" src="{% static 'img/prestamo/logo-slogan-blanco.webp' %}" alt="Logi de Moni.com">
        <img class="prestamo__monipose" src="{% static 'img/prestamo/moni-pose.svg' %}" alt="Moni Pose">
    </div>
    <div class="prestamo__lateralDerecho">
        <h2 class="prestamo__titulo">MONI</h2>
        <h3 class="prestamo__subtitulo">¿Queres solicitar un prestamo?</h3>
        <h3 class="prestamo__tituloForm">Completa el siguiente formulario</h3>
        <form action="{% url 'web:solicitar_prestamo' %}" method="POST" id="prestamo__formulario" class="prestamo__formulario">{% csrf_token %}
            {% for fila in prestamoForm %}
                <div class="prestamo__formulario--item">
                    {{ fila.label_tag }}
                    {{ fila }}
                </div>
            {% endfor %}
            <div class="prestamo__formulario--error" id="prestamo_mensaje"></div>
            <div class="prestamo__formulario--item">
                <button class="prestamo__submit" type="submit">Solicitar</button>
            </div> 
        </form>
    </div>
    </section>
{{prestamoForm.media}}   
{% endblock main %}